# model
model: "efficientnetb4"          # resnet50, xception, efficientnetb4
num_classes: 10
dropout_rate: 0.0

# training
num_epochs: 30
batch_size: 64
patience: 5
seed: 42
device: "mps"              # cpu, cuda, mps

# optimizer
optimizer: "adam"           # sgd, adam
learning_rate: 0.001
momentum: 0.9              # only for sgd

# regularization
regularization: "l1"  # l1, l2, null
lambda_param: !!float 1e-3

# scheduler
scheduler: "cosine"        # cosine

# data
train_dir: "./data/train"
val_dir:   "./data/valid"

# transforms
preset: "none"           # none, light, medium, heavy 
augmentor_config: null #"code/configs/augmentor.yaml" # None if no augmentor

# paths
model_path: "./saved_models"