# model
model: "xception"          # resnet50, xception, efficientnetb4
num_classes: 10
dropout_rate: 0.0

# training
num_epochs: 30
batch_size: 64
patience: 5
seed: 42
device: "cuda"              # cpu, cuda, mps

# optimizer
optimizer: "adam"           # sgd, adam
learning_rate: 0.01
momentum: 0.9              # only for sgd

# scheduler
scheduler: "cosine"        # cosine

# data
train_dir: "./data/train"
val_dir:   "./data/valid"

# transforms
preset: "none"           # none, light, medium, heavy 
augmentor_config: "None" #"code/configs/augmentor.yaml" # None if no augmentor

# paths
model_path: "./saved_models"